apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3080
      protocol: TCP
      name: http
  # pods selector for routing traffic
  selector:
    app: demo