name: Build
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: j6uluh2kk
      REPO: ${GITHUB_REPOSITORY#*/}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCR_J6ULUH2KK_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      # Build docker image
      - name: Image
        run: |-
          docker build --tag eu.gcr.io/$PROJECT_ID/$REPO:$GITHUB_SHA .
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Push
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$REPO:$GITHUB_SHA