name: Build
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: j6uluh2kk
      REPO: ${{github.repository}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_J6ULUH2KK_SERVICE_ACCOUNT_KEY }}
          project_id: j6uluh2kk
          export_default_credentials: true

      # Build docker image
      - name: Image
        run: |-
          docker build --build-arg -t eu.gcr.io/$PROJECT_ID/$REPO:$GITHUB_SHA .
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Push
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$REPO:$GITHUB_SHA